# Generated by Django 6.0.2 on 2026-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
