# Generated by Django 6.0.2 on 2026-03-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksessions', '0002_sessionapplication_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedsession',
            name='speaker_names',
            field=models.CharField(blank=True, help_text='Used for manually added sessions without a linked application.', max_length=300),
        ),
    ]
