# Generated by Django 6.0.2 on 2026-03-03 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksessions', '0003_approvedsession_speaker_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='applicationspeaker',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='applicationspeaker',
            name='speaker_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='applicationspeaker',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationspeaker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='applicationspeaker',
            unique_together={('application', 'speaker_email')},
        ),
    ]
