# Generated by Django 6.0.2 on 2026-03-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksessions', '0004_departmentmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedsession',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='sessionapplication',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
